detalles

diff --git a/tanos/respaldomes b/tanos/respaldomes
--- a/tanos/respaldomes
+++ b/tanos/respaldomes
@@ -25,35 +25,35 @@ function init() {
     rm -f "$BACKUP_DIR/semanal/gpc-snapshot.snar" "$BACKUP_DIR/diario/gpc-snapshot.snar"
     echo "[$(date)] Respaldos diario y semanal eliminados" >> "$LOGFILE"
 
-    # mysqldump -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" | gzip > "$FULL_DIR/$DB_BACKUP_NAME"
-    # echo "[$(date)] Respaldo de base de datos realizado: $DB_BACKUP_NAME" >> "$LOGFILE"
+    mysqldump -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" | gzip > "$FULL_DIR/$DB_BACKUP_NAME"
+    echo "[$(date)] Respaldo de base de datos realizado: $DB_BACKUP_NAME" >> "$LOGFILE"
 
     tar --listed-incremental="$SNAPSHOT_FILE" -czpf "$FULL_DIR/$FILES_BACKUP_NAME" /etc --exclude="$BACKUP_DIR"
     echo "[$(date)] Respaldo de archivos realizado: $FILES_BACKUP_NAME" >> "$LOGFILE"
 
-    # sha256sum "$FULL_DIR/$DB_BACKUP_NAME" > "$FULL_DIR/$DB_BACKUP_NAME.sha256"
-    # echo "[$(date)] Checksum generado para base de datos: $DB_BACKUP_NAME.sha256" >> "$LOGFILE"
+    sha256sum "$FULL_DIR/$DB_BACKUP_NAME" > "$FULL_DIR/$DB_BACKUP_NAME.sha256"
+    echo "[$(date)] Checksum generado para base de datos: $DB_BACKUP_NAME.sha256" >> "$LOGFILE"
 
     sha256sum "$FULL_DIR/$FILES_BACKUP_NAME" > "$FULL_DIR/$FILES_BACKUP_NAME.sha256"
     echo "[$(date)] Checksum generado para archivos: $FILES_BACKUP_NAME.sha256" >> "$LOGFILE"
 
-    # scp "$FULL_DIR/$DB_BACKUP_NAME" "$FULL_DIR/$DB_BACKUP_NAME.sha256" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH/"
-    # echo "[$(date)] Respaldo de base de datos transferido a remoto" >> "$LOGFILE"
+    scp "$FULL_DIR/$DB_BACKUP_NAME" "$FULL_DIR/$DB_BACKUP_NAME.sha256" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH/"
+    echo "[$(date)] Respaldo de base de datos transferido a remoto" >> "$LOGFILE"
 
     scp "$FULL_DIR/$FILES_BACKUP_NAME" "$FULL_DIR/$FILES_BACKUP_NAME.sha256" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH/"
     echo "[$(date)] Respaldo de archivos transferido a remoto" >> "$LOGFILE"
 
-    # ssh "$REMOTE_USER@$REMOTE_HOST" "cd $REMOTE_PATH && \
-    #     sha256sum -c $DB_BACKUP_NAME.sha256 && \
-    #     sha256sum -c $FILES_BACKUP_NAME.sha256"
+    ssh "$REMOTE_USER@$REMOTE_HOST" "cd $REMOTE_PATH && \
+        sha256sum -c $DB_BACKUP_NAME.sha256 && \
+        sha256sum -c $FILES_BACKUP_NAME.sha256"
 
-    # if [ $? -eq 0 ]; then
-    #     echo "[$(date)] Respaldo mensual completado exitosamente" >> "$LOGFILE"
-    #     exit 0
-    # else
-    #     echo "[$(date)] Error en respaldo mensual" >> "$LOGFILE"
-    #     exit 1
-    # fi
+    if [ $? -eq 0 ]; then
+        echo "[$(date)] Respaldo mensual completado exitosamente" >> "$LOGFILE"
+        exit 0
+    else
+        echo "[$(date)] Error en respaldo mensual" >> "$LOGFILE"
+        exit 1
+    fi
 }
 
-init "$@"
+# init "$@"
diff --git a/tanos/respaldosemana b/tanos/respaldosemana
--- a/tanos/respaldosemana
+++ b/tanos/respaldosemana
@@ -24,32 +24,32 @@ function init() {
     rm -rf "$BACKUP_DIR/diario/*"
     echo "[$(date)] Respaldos diarios eliminados de $BACKUP_DIR/diario" >> "$LOGFILE"
 
-    # mysqldump -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" | gzip > "$DIFF_DIR/$DB_BACKUP_NAME"
-    # echo "[$(date)] Respaldo de base de datos realizado: $DIFF_DIR/$DB_BACKUP_NAME" >> "$LOGFILE"
+    mysqldump -u "$DB_USER" -p"$DB_PASS" "$DB_NAME" | gzip > "$DIFF_DIR/$DB_BACKUP_NAME"
+    echo "[$(date)] Respaldo de base de datos realizado: $DIFF_DIR/$DB_BACKUP_NAME" >> "$LOGFILE"
     tar --listed-incremental="$SNAPSHOT_FILE" -czpf "$DIFF_DIR/$FILES_BACKUP_NAME" /etc --exclude="$BACKUP_DIR"
     echo "[$(date)] Respaldo diferencial semanal de archivos realizado: $DIFF_DIR/$FILES_BACKUP_NAME" >> "$LOGFILE"
 
-    # sha256sum "$DIFF_DIR/$DB_BACKUP_NAME" > "$DIFF_DIR/$DB_BACKUP_NAME.sha256"
-    # echo "[$(date)] Checksum generado para respaldo de base de datos: $DIFF_DIR/$DB_BACKUP_NAME.sha256" >> "$LOGFILE"
+    sha256sum "$DIFF_DIR/$DB_BACKUP_NAME" > "$DIFF_DIR/$DB_BACKUP_NAME.sha256"
+    echo "[$(date)] Checksum generado para respaldo de base de datos: $DIFF_DIR/$DB_BACKUP_NAME.sha256" >> "$LOGFILE"
     sha256sum "$DIFF_DIR/$FILES_BACKUP_NAME" > "$DIFF_DIR/$FILES_BACKUP_NAME.sha256"
     echo "[$(date)] Checksum generado para respaldo de archivos: $DIFF_DIR/$FILES_BACKUP_NAME.sha256" >> "$LOGFILE"
 
-    # scp "$DIFF_DIR/$DB_BACKUP_NAME" "$DIFF_DIR/$DB_BACKUP_NAME.sha256" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH/"
-    # echo "[$(date)] Respaldo de base de datos y checksum enviados a remoto" >> "$LOGFILE"
+    scp "$DIFF_DIR/$DB_BACKUP_NAME" "$DIFF_DIR/$DB_BACKUP_NAME.sha256" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH/"
+    echo "[$(date)] Respaldo de base de datos y checksum enviados a remoto" >> "$LOGFILE"
     scp "$DIFF_DIR/$FILES_BACKUP_NAME" "$DIFF_DIR/$FILES_BACKUP_NAME.sha256" "$REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH/"
     echo "[$(date)] Respaldo de archivos y checksum enviados a remoto" >> "$LOGFILE"
 
-    # ssh "$REMOTE_USER@$REMOTE_HOST" "cd $REMOTE_PATH && \
-    #     sha256sum -c $DB_BACKUP_NAME.sha256 && \
-    #     sha256sum -c $FILES_BACKUP_NAME.sha256"
+    ssh "$REMOTE_USER@$REMOTE_HOST" "cd $REMOTE_PATH && \
+        sha256sum -c $DB_BACKUP_NAME.sha256 && \
+        sha256sum -c $FILES_BACKUP_NAME.sha256"
 
-    # if [ $? -eq 0 ]; then
-    #     echo "[$(date)] Verificación exitosa, respaldo semanal completado" >> "$LOGFILE"
-    #     exit 0
-    # else
-    #     echo "[$(date)] Error en la verificación, respaldo semanal fallido" >> "$LOGFILE"
-    #     exit 1
-    # fi
+    if [ $? -eq 0 ]; then
+        echo "[$(date)] Verificación exitosa, respaldo semanal completado" >> "$LOGFILE"
+        exit 0
+    else
+        echo "[$(date)] Error en la verificación, respaldo semanal fallido" >> "$LOGFILE"
+        exit 1
+    fi
 }
 
-init "$@"
+# init "$@"
